[package]
authors = ["Tim Neumann <mail@timnn.me>"]
name = "pcp"
version = "0.1.0"

[dependencies]
clap = "1.5.2"
libc = "0.2.2"
num_cpus = "0.2.7"
scoped_threadpool = "0.1.6"

[profile]

[profile.release]
debug = true
lto = true
